"""add supplier receipts

Revision ID: ce922bf1c0c6
Revises: e73124c3e89a
Create Date: 2026-09-17 17:57:02.585043
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ce922bf1c0c6"
down_revision: str | Sequence[str] | None = "e73124c3e89a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "READY_FOR_REVIEW",
                "CONFIRMED",
                "FAILED",
                "CANCELLED",
                name="receiptstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=40), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("supplier_name", sa.String(length=120), nullable=True),
        sa.Column("receipt_number", sa.String(length=64), nullable=True),
        sa.Column("receipt_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("extracted_subtotal", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("extracted_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("extraction_provider", sa.String(length=40), nullable=True),
        sa.Column("extraction_model", sa.String(length=60), nullable=True),
        sa.Column("extraction_error", sa.String(length=255), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('UPLOADED', 'PROCESSING', 'READY_FOR_REVIEW', 'CONFIRMED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_receipts_status"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_receipts_size_positive")),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_receipts_business_id_businesses")
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"], ["users.id"], name=op.f("fk_receipts_confirmed_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_receipts_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("id", "business_id", name=op.f("uq_receipts_id_business_id")),
    )
    op.create_index(
        op.f("ix_receipts_business_id_created_at"),
        "receipts",
        ["business_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receipts_business_id_status"), "receipts", ["business_id", "status"], unique=False
    )
    op.create_table(
        "receipt_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("extracted_name", sa.String(length=160), nullable=False),
        sa.Column("extracted_sku", sa.String(length=64), nullable=True),
        sa.Column("extracted_quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("extracted_unit_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("extracted_line_total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "match_status",
            sa.Enum(
                "MATCHED",
                "AMBIGUOUS",
                "UNMATCHED",
                name="receiptmatchstatus",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("matched_product_id", sa.UUID(), nullable=True),
        sa.Column("candidate_product_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "PENDING",
                "APPLIED",
                "SKIPPED",
                name="receiptlinereview",
                native_enum=False,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("final_product_id", sa.UUID(), nullable=True),
        sa.Column("final_quantity", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("final_unit_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("movement_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_status IN ('MATCHED', 'AMBIGUOUS', 'UNMATCHED')",
            name=op.f("ck_receipt_lines_match_status"),
        ),
        sa.CheckConstraint(
            "review_status IN ('PENDING', 'APPLIED', 'SKIPPED')",
            name=op.f("ck_receipt_lines_review_status"),
        ),
        sa.CheckConstraint(
            "extracted_quantity > 0", name=op.f("ck_receipt_lines_extracted_quantity_positive")
        ),
        sa.CheckConstraint(
            "extracted_unit_cost >= 0",
            name=op.f("ck_receipt_lines_extracted_unit_cost_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["business_id"], ["businesses.id"], name=op.f("fk_receipt_lines_business_id_businesses")
        ),
        sa.ForeignKeyConstraint(
            ["matched_product_id", "business_id"],
            ["products.id", "products.business_id"],
            name=op.f("fk_receipt_lines_matched_product_id_business_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["movement_id"],
            ["inventory_movements.id"],
            name=op.f("fk_receipt_lines_movement_id_inventory_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id", "business_id"],
            ["receipts.id", "receipts.business_id"],
            name=op.f("fk_receipt_lines_receipt_id_business_id_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_lines")),
    )
    op.create_index(
        op.f("ix_receipt_lines_receipt_id_position"),
        "receipt_lines",
        ["receipt_id", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_lines_receipt_id_position"), table_name="receipt_lines")
    op.drop_table("receipt_lines")
    op.drop_index(op.f("ix_receipts_business_id_status"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_business_id_created_at"), table_name="receipts")
    op.drop_table("receipts")
    # ### end Alembic commands ###
